support file metadata
DEFRA/fcp-fd-data pull request #17
Opened 2024-12-19 12:55 UTC by simonnineteen90

https://eaflood.atlassian.net/browse/SFDP-125

2025-01-08 09:06 UTC, simonnineteen90 commented on app/messaging/process-inbound-message.js
Using eslint-disable here to use `hasOwnProperty` until we update the aysncapi and use cloudevents `type` to identify the type of message.

2025-01-08 09:47 UTC, sfitz42 requested changes
Just a couple of smallish changes

2025-01-08 09:47 UTC, sfitz42 commented on app/messaging/process-inbound-message.js
As each switch case is just a function call I would just return the function so we don't need the break. Not a massive issue though won't lose sleep 🤣

2025-01-08 09:47 UTC, sfitz42 commented on docker-compose.yaml
> +      COMMS_TOPIC_ADDRESS: ${COMMS_TOPIC_ADDRESS:-fcp-fd-data}-${MESSAGE_QUEUE_SUFFIX}
Should the prefix for these not be `DATA_` rather than `COMMS_`?

2025-01-08 09:47 UTC, sfitz42 commented on docker-compose.yaml
> +      COMMS_TOPIC_ADDRESS: ${COMMS_TOPIC_ADDRESS:-fcp-fd-data}-${MESSAGE_QUEUE_SUFFIX}
I think the `azure.provision.yaml` was raised in the past and John said it needed to match here. I'm wondering if this is why he thought comms was correct?

2025-01-08 09:47 UTC, sfitz42 commented on docs/asyncapi.yaml
>      commsMessage:
We could use a schema for the CloudEvent types. Only thing that will change between the two will be anything in data.

2025-01-08 10:15 UTC, simonnineteen90 commented on docker-compose.yaml
> +      COMMS_TOPIC_ADDRESS: ${COMMS_TOPIC_ADDRESS:-fcp-fd-data}-${MESSAGE_QUEUE_SUFFIX}
Yeah i remember going over this before but agree it should be `DATA`

2025-01-08 10:52 UTC, simonnineteen90 commented on docs/asyncapi.yaml
>      commsMessage:
This can be implemented when we change the schema to use cloudevents 
https://eaflood.atlassian.net/browse/SFDP-139

2025-01-13 09:21 UTC, sfitz42 approved these changes
LGTM

2025-01-13 10:27 UTC, merged